# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xqbb74kwp6SXMSz6XeYzJfltsrPXAHaQ
"""

# hanoi towers

def mostrarSecuencia(start,end):
  print(start, " -> " , end)


def hanoi(n, inicio , destino):
  if n == 1:
    mostrarSecuencia(inicio,destino)
  else : 
    otro = 6 - (inicio + destino)
    hanoi( n - 1 , inicio , otro)
    mostrarSecuencia(inicio,destino)
    hanoi( n - 1 , otro , destino)




hanoi(3,inicio = 1,destino = 3)

# hanoi towers

def mostrarSecuencia(start,end):

  print(start, " -> " , end)
  

def hanoi(n, inicio , destino):
  if n == 1:
    mostrarSecuencia(inicio,destino)
  else : 
    otro = 6 - (inicio + destino) 
    hanoi( n - 1 , inicio , otro) ; print("h(" , n -1 , inicio , otro ,")")
    mostrarSecuencia(inicio,destino)
    hanoi( n - 1 , otro , destino) ; print("h(" , n - 1 , otro , destino ,")")




hanoi(3,inicio = 1,destino = 3)


#1  ->  3
#h( 1 1 3 )
#1  ->  2
#3  ->  2
#h( 1 3 2 )
#h( 2 1 2 )
#1  ->  3
#2  ->  1
#h( 1 2 1 )
#2  ->  3
#1  ->  3
#h( 1 1 3 )
#h( 2 2 3 )

hanoi(4,inicio = 1,destino = 3)